### ISSUE TITLE
s1 metric heatmaps have trouble with NaNs

### ISSUE THREAD

**Issue by iebert** [ai2es/sharpness#19]
When calculating the heatmaps for the s1 metric there is a problem when NaNs are encountered.  It handles the NaNs well during calculation, but then wants to print a warning on the screen that NaNs are encountered - and that's where it stops with an error.

**Comment by iebert** [comment]
Error message:

File ~/anaconda3/envs/ai2es-sharpness/lib/python3.8/site-packages/sharpness-0.1.0-py3.8.egg/sharpness/heatmap.py:106, in Heatmap(img1, img2, metric, block_size, pad_len, pad_mode, block_stride, bivariate)
    104 if np.any(np.isnan(res)):
    105     if type(res) is list:
--> 106         print(f'NaNs encountered in {metric.__name__}:\n'
    107               f'{np.sum(np.isnan(res[0]))} NaNs out of {np.prod(res[0].shape)} total blocks in image 0\n'
    108               f'{np.sum(np.isnan(res[1]))} NaNs out of {np.prod(res[1].shape)} total blocks in image 1')
    109     else:
    110         print(f'NaNs encountered in {metric.__name__}: {np.sum(np.isnan(res))} NaNs out of {np.prod(res.shape)} total blocks')

AttributeError: 'functools.partial' object has no attribute '__name__'

**Comment by zyjux** [comment]
I added a line in "metric_list.py" that sets the `__name__` attribute for s1 manually to work around this, and pushed this fix in commit 4c646d0a1def175fd7a301f38f0d0c74acdb2f4d, so these errors should no longer occur.
