### ISSUE TITLE
environment.yml file suggestions

### ISSUE THREAD

**Issue by iebert** [ai2es/sharpness#7]
Two suggestions: 
1) Change name of environment from ai2es to ai2es-sharpness.  Otherwise we may run into trouble later with environments for different ai2es repos having the same name. 
2) Looks like scikit-image is missing in list of packages to be installed.

**Comment by zyjux** [comment]
It looks like scikit-image got added to the list of packages to be installed, and I just changed the name to the suggested one in commit 7863868.
